/**
 * DealFlow360 — Universal Report Export Engine (PDF & XLS)
 * Generates formatted executive PDF reports and structured multi-sheet Excel workbooks.
 */

import { jsPDF } from 'jspdf';
import * as XLSX from 'xlsx';
import {
  ReportFilters,
  ReportKPIs,
  Quotation,
  CategoryReportItem,
  RepPerformanceItem,
  ApprovalPerformanceItem,
} from '../types';
import { formatCurrency, formatPercent } from '../utils/formatters';

export interface ExportReportPayload {
  title: string;
  generatedAt: string;
  generatedBy: string;
  filters: ReportFilters;
  kpis: ReportKPIs;
  quotations: Quotation[];
  categoryBreakdown: CategoryReportItem[];
  repPerformance: RepPerformanceItem[];
  approvalPerformance: ApprovalPerformanceItem[];
}

/**
 * Generates and downloads a clean, multi-page executive PDF report.
 */
export function exportReportToPDF(payload: ExportReportPayload): void {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  let y = 16;

  // Header Bar
  doc.setFillColor(88, 28, 135); // Deep Plum (#581c87)
  doc.rect(14, y, pageWidth - 28, 14, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(13);
  doc.setFont('helvetica', 'bold');
  doc.text('DEALFLOW360 — COMMERCIAL GOVERNANCE & AUDIT REPORT', 18, y + 9);

  y += 20;

  // Metadata block
  doc.setTextColor(51, 65, 85);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.text(`Generated: ${payload.generatedAt}`, 14, y);
  doc.text(`Generated By: ${payload.generatedBy}`, 14, y + 5);
  doc.text(
    `Filters: Period: ${payload.filters.period} | Team: ${payload.filters.salesTeam || 'All'} | Status: ${payload.filters.approvalStatus || payload.filters.stage || 'All'} | Category: ${payload.filters.category || 'All'}`,
    14,
    y + 10
  );

  y += 18;

  // Section Header: Core Executive KPIs
  doc.setFillColor(241, 245, 249);
  doc.rect(14, y, pageWidth - 28, 7, 'F');
  doc.setTextColor(30, 41, 59);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  doc.text('CORE EXECUTIVE REVENUE & GOVERNANCE KPIS', 16, y + 5);

  y += 11;

  // KPI Grid (5 cards)
  const kpiItems = [
    { label: 'Quotes Created', val: `${payload.kpis.quotesCreated}` },
    { label: 'Total Pipeline', val: formatCurrency(payload.kpis.totalPipelineValue) },
    { label: 'Blended Margin', val: formatPercent(payload.kpis.blendedMarginRate) },
    { label: 'Avg Approval Velocity', val: `${payload.kpis.averageApprovalTimeHours} hrs` },
    { label: 'Top Upsold Product', val: payload.kpis.topUpsoldProduct },
  ];

  const colWidth = (pageWidth - 28) / kpiItems.length;
  kpiItems.forEach((item, index) => {
    const x = 14 + index * colWidth;
    doc.setDrawColor(226, 232, 240);
    doc.setFillColor(248, 250, 252);
    doc.roundedRect(x, y, colWidth - 2, 16, 1, 1, 'FD');

    doc.setFontSize(7.5);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(100, 116, 139);
    doc.text(item.label, x + 2.5, y + 5);

    doc.setFontSize(9);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(15, 23, 42);
    doc.text(item.val.length > 18 ? item.val.slice(0, 17) + '…' : item.val, x + 2.5, y + 11.5);
  });

  y += 23;

  // Section: Quotations Pipeline Ledger
  doc.setFillColor(241, 245, 249);
  doc.rect(14, y, pageWidth - 28, 7, 'F');
  doc.setTextColor(30, 41, 59);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  doc.text(`QUOTATIONS PIPELINE (${payload.quotations.length} DEALS)`, 16, y + 5);

  y += 10;

  // Table header
  doc.setFillColor(226, 232, 240);
  doc.rect(14, y, pageWidth - 28, 6, 'F');
  doc.setFontSize(7.5);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(51, 65, 85);
  doc.text('Quote Code', 16, y + 4.2);
  doc.text('Customer', 42, y + 4.2);
  doc.text('Sales Rep', 84, y + 4.2);
  doc.text('Stage', 120, y + 4.2);
  doc.text('Net Value', 148, y + 4.2);
  doc.text('Margin %', 174, y + 4.2);

  y += 7;

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(7.5);

  // Rows (limit to first 18 for neat page fit or paginate)
  const displayQuotes = payload.quotations.slice(0, 16);
  displayQuotes.forEach((q, idx) => {
    if (idx % 2 === 1) {
      doc.setFillColor(248, 250, 252);
      doc.rect(14, y - 1, pageWidth - 28, 5.5, 'F');
    }
    doc.setTextColor(30, 41, 59);
    doc.text(q.code || q.id, 16, y + 3);
    doc.text((q.customerName || 'Customer').slice(0, 22), 42, y + 3);
    doc.text((q.repName || 'Sales Rep').slice(0, 18), 84, y + 3);
    doc.text(q.stage || 'Draft', 120, y + 3);
    doc.text(formatCurrency(q.netAmount ?? q.revenue ?? q.grandTotal), 148, y + 3);
    doc.text(formatPercent(q.marginPercent ?? q.blendedMarginPercent), 174, y + 3);
    y += 5.5;
  });

  if (payload.quotations.length > 16) {
    doc.setFontSize(7);
    doc.setTextColor(100, 116, 139);
    doc.text(
      `... and ${payload.quotations.length - 16} additional quotation records. (See complete data in XLS export)`,
      16,
      y + 3
    );
    y += 7;
  }

  y += 4;

  // Section: Category Breakdown
  if (y < 230) {
    doc.setFillColor(241, 245, 249);
    doc.rect(14, y, pageWidth - 28, 7, 'F');
    doc.setTextColor(30, 41, 59);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(10);
    doc.text('PRODUCT CATEGORY MARGIN & REVENUE BREAKDOWN', 16, y + 5);

    y += 10;

    doc.setFillColor(226, 232, 240);
    doc.rect(14, y, pageWidth - 28, 6, 'F');
    doc.setFontSize(7.5);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(51, 65, 85);
    doc.text('Category', 16, y + 4.2);
    doc.text('Units Quoted', 60, y + 4.2);
    doc.text('Revenue', 95, y + 4.2);
    doc.text('Cost', 130, y + 4.2);
    doc.text('Gross Profit', 158, y + 4.2);
    doc.text('Margin %', 182, y + 4.2);

    y += 7;

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(7.5);

    payload.categoryBreakdown.forEach((cat, idx) => {
      if (idx % 2 === 1) {
        doc.setFillColor(248, 250, 252);
        doc.rect(14, y - 1, pageWidth - 28, 5.5, 'F');
      }
      doc.setTextColor(30, 41, 59);
      doc.text(cat.category, 16, y + 3);
      doc.text(`${cat.itemCount}`, 60, y + 3);
      doc.text(formatCurrency(cat.revenue), 95, y + 3);
      doc.text(formatCurrency(cat.cost), 130, y + 3);
      doc.text(formatCurrency(cat.profit), 158, y + 3);
      doc.text(formatPercent(cat.marginPercent), 182, y + 3);
      y += 5.5;
    });
  }

  // Footer on bottom of page
  doc.setFontSize(7);
  doc.setTextColor(148, 163, 184);
  doc.text(
    'DealFlow360 Enterprise ERP • Confidential Revenue Desk & Audit Governance Document • Page 1 of 1',
    14,
    285
  );

  const cleanPeriod = (payload.filters.period || 'All').replace(/\s+/g, '_');
  const filename = `DealFlow360_Report_${cleanPeriod}_${new Date().toISOString().slice(0, 10)}.pdf`;
  doc.save(filename);
}

/**
 * Generates and downloads a structured multi-sheet Excel (.xlsx) workbook.
 */
export function exportReportToXLS(payload: ExportReportPayload): void {
  const wb = XLSX.utils.book_new();

  // 1. Executive Summary Sheet
  const kpiSheetData = [
    ['DealFlow360 Commercial Governance & Executive Reporting'],
    ['Generated At', payload.generatedAt],
    ['Generated By', payload.generatedBy],
    ['Applied Period Filter', payload.filters.period],
    ['Applied Sales Team', payload.filters.salesTeam || 'All'],
    ['Applied Rep', payload.filters.repId || 'All'],
    ['Applied Stage / Approval', payload.filters.approvalStatus || payload.filters.stage || 'All'],
    ['Applied Category', payload.filters.category || 'All'],
    [],
    ['KEY PERFORMANCE INDICATORS', 'VALUE'],
    ['Quotes Created', payload.kpis.quotesCreated],
    ['Total Pipeline Value ($)', payload.kpis.totalPipelineValue],
    ['Blended Margin Rate (%)', `${payload.kpis.blendedMarginRate}%`],
    ['Average Approval Time (Hours)', `${payload.kpis.averageApprovalTimeHours} hrs`],
    ['Top Upsold Product', payload.kpis.topUpsoldProduct],
    ['Approved Deals Count', payload.kpis.approvedCount],
    ['Pending Approval Count', payload.kpis.pendingApprovalCount],
    ['Rejected Deals Count', payload.kpis.rejectedCount],
    ['Average Discount (%)', `${payload.kpis.averageDiscountPercent}%`],
    ['Win / Conversion Rate (%)', `${payload.kpis.wonRatePercent}%`],
  ];
  const wsSummary = XLSX.utils.aoa_to_sheet(kpiSheetData);
  XLSX.utils.book_append_sheet(wb, wsSummary, 'KPI Summary');

  // 2. Quotations Pipeline Sheet
  const quoteRows = payload.quotations.map((q) => ({
    'Quotation Code': q.code || q.id,
    Customer: q.customerName || 'N/A',
    Tier: q.customerTier || q.priceListTier || 'Standard',
    'Sales Rep': q.repName || 'N/A',
    Stage: q.stage,
    Subtotal: q.subtotal || 0,
    Discount: q.totalDiscount || q.totalDiscountAmount || 0,
    'Net Revenue': q.netAmount ?? q.revenue ?? q.grandTotal ?? 0,
    Cost: q.cost || 0,
    Profit: q.profit || 0,
    'Margin %': q.marginPercent ?? q.blendedMarginPercent ?? 0,
    'Risk Level': q.blendedRiskValue || q.blendedRiskLevel || 'LOW',
    'Created Date': q.createdAt || 'N/A',
    'Last Activity': q.lastActivityAt || q.updatedAt || 'N/A',
  }));
  const wsQuotes = XLSX.utils.json_to_sheet(quoteRows);
  XLSX.utils.book_append_sheet(wb, wsQuotes, 'Quotations');

  // 3. Category Breakdown Sheet
  const categoryRows = payload.categoryBreakdown.map((c) => ({
    Category: c.category,
    'Total Units / Items': c.itemCount,
    'Gross Subtotal ($)': c.subtotal,
    'Total Discounts ($)': c.discountAmount,
    'Net Revenue ($)': c.revenue,
    'Cost ($)': c.cost,
    'Gross Profit ($)': c.profit,
    'Margin Rate (%)': `${c.marginPercent}%`,
    'Share of Total Revenue (%)': `${c.revenueSharePercent}%`,
  }));
  const wsCategory = XLSX.utils.json_to_sheet(categoryRows);
  XLSX.utils.book_append_sheet(wb, wsCategory, 'Category Breakdown');

  // 4. Sales Rep Scorecard Sheet
  const repRows = payload.repPerformance.map((r) => ({
    'Rep Name': r.repName,
    Department: r.department,
    'Quotes Created': r.quotesCount,
    'Pipeline Value ($)': r.pipelineValue,
    'Average Deal Size ($)': r.averageDealSize,
    'Average Discount (%)': `${r.averageDiscountPercent}%`,
    'Blended Margin (%)': `${r.blendedMarginPercent}%`,
    'Approved Deals': r.approvedCount,
    'Win Rate (%)': `${r.winRatePercent}%`,
  }));
  const wsReps = XLSX.utils.json_to_sheet(repRows);
  XLSX.utils.book_append_sheet(wb, wsReps, 'Sales Rep Scorecard');

  // 5. Approval Governance & Velocity Sheet
  const approvalRows = payload.approvalPerformance.map((a) => ({
    'Quotation Code': a.quotationCode,
    Customer: a.customerName,
    Step: a.stepOrder,
    'Approver Role': a.approverRole,
    'Approver Name': a.approverName,
    Status: a.status,
    'Submitted At': a.submittedAt,
    'Decided At': a.decidedAt || 'Pending',
    'Turnaround Hours': a.turnaroundHours,
    'Max Discount Over Limit (pts)': `+${a.maxDiscountOverLimit}%`,
    Note: a.note || '',
  }));
  const wsApprovals = XLSX.utils.json_to_sheet(approvalRows);
  XLSX.utils.book_append_sheet(wb, wsApprovals, 'Approval Governance');

  const cleanPeriod = (payload.filters.period || 'All').replace(/\s+/g, '_');
  const filename = `DealFlow360_Report_${cleanPeriod}_${new Date().toISOString().slice(0, 10)}.xlsx`;
  XLSX.writeFile(wb, filename);
}
